### ISSUE TITLE
missing magrittr_hex.png

### ISSUE THREAD

**Issue by paciorek** [berkeley-scf/r-bootcamp-2018#2]
@nhejazi looks like you added ![](img/magrittr_hex.png) in module6_tidyverse.Rmd but didn't commit the png file to the repo?

**Comment by paciorek** [comment]
also, @nhejazi I think you might have (perhaps inadvertently) added the data/stackoverflow-2016.db file to the repo. I want to keep this out as it is 650 MB and I don't want students to have to pull that big a file down. So with any additional commits, please check that is not added back in.

**Comment by nhejazi** [comment]
@paciorek --- apologies for the oversight in not including the image file `magrittr_hex.png` and for committing the `data/stackoverflow-2016.db` data set (I didn't realize this was created by the code within the modules). I've just open PR #3, which should resolve these issues.

**Comment by paciorek** [comment]
Thanks. 

Sidenote: the .db shouldn't be created by the code. Perhaps you downloaded it and it somehow got added to your commit? In any event, no worries.

**Comment by nhejazi** [comment]
No problem; sorry again for the mixup. I'll go ahead and merge #3 and close this issue as resolved.
